// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCAYwMWQlIC6sQoAEGYJyf5a_CriLsKKmI',
//     appId: '1:42941591402:web:b63043e8c13a811ca7ff13',
//     messagingSenderId: '42941591402',
//     projectId: 'flutter-login-2c625',
//     authDomain: 'flutter-login-2c625.firebaseapp.com',
//     storageBucket: 'flutter-login-2c625.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBHpFpz_NX80XyACZ0pHkR-fBBgMG5rWAA',
//     appId: '1:42941591402:android:3c42cea822a5c428a7ff13',
//     messagingSenderId: '42941591402',
//     projectId: 'flutter-login-2c625',
//     storageBucket: 'flutter-login-2c625.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBU8RncAjBwes7dmztKpY9qEqlZ6vn7Vg0',
//     appId: '1:42941591402:ios:525fa4ff4a0bab61a7ff13',
//     messagingSenderId: '42941591402',
//     projectId: 'flutter-login-2c625',
//     storageBucket: 'flutter-login-2c625.appspot.com',
//     iosClientId: '42941591402-esdrpqcpt170oapje643b5hs0jfeqi7f.apps.googleusercontent.com',
//     iosBundleId: 'com.example.fire',
//   );
// }
